<a href="https://colab.research.google.com/github/RohitKumar1608/AI_ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  # Numpy takes list as an input and convert it to ndarray
import numpy as np

carlst = ['Tesla','Tata','Ford','Nissan']
lst=np.array(carlst)
print(lst)

['Tesla' 'Tata' 'Ford' 'Nissan']


In [ ]:
# Matrix
lst= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(lst)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#arange
ndarr= np.arange(0,10,2)
print(ndarr)

[0 2 4 6 8]


In [ ]:
# linspace
ndarr=np.linspace(0,5,10)
print(ndarr)

ndarr=np.linspace(10,20,10)
print(ndarr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [ ]:
# ZEROS (ROW, COLUMN)
ndarr = np.zeros ([3,5])
ndarr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# ONES (ROW,COLUM)
ndarr=np.ones([3,5])
ndarr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ndarr=np.eye(3)
print(ndarr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Reshape
# Reshape don't alter the ndarr but can be asigned to new numpy array
ndarr=np.arange(0,10)
print(ndarr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(ndarr.reshape(2,5))
print(ndarr.reshape(5,2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(np.sin(4))
print(np.cos(4))
print(np.tan(4))
print(np.sin(ndarr))

-0.7568024953079282
-0.6536436208636119
1.1578212823495775
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [ ]:
# exponential
print(np.exp(2))
print(np.exp(ndarr))

7.38905609893065
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [ ]:
print(np.log(2.71))
print(np.log10(10))

0.9969486348916096
1.0


In [ ]:
# Adding list concatenate the two list
l1= [1,2,3]
l2 =[4,5,6]
l1+l2

[1, 2, 3, 4, 5, 6]

In [ ]:
l1= [1,2,3]
l2 =[4,5,6]
ndarr =np.array(l1) + np.array(l2)
ndarr

array([5, 7, 9])

In [ ]:
arr1 = np.arange(1,6)
arr2 = np.arange(3,8)
print("addition", arr1+arr2)
print("substraction", arr2-arr1)
print("Multiplication", arr1 * arr2)
print("Division", arr1/arr2)
print("Inverse", 1/arr1)
print("Power", arr1 ** arr2)

addition [ 4  6  8 10 12]
substraction [2 2 2 2 2]
Multiplication [ 3  8 15 24 35]
Division [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse [1.         0.5        0.33333333 0.25       0.2       ]
Power [    1    16   243  4096 78125]


In [ ]:
# MATRIX OPERATION
ndarr1= np.arange(1,10).reshape(3,3)
print(ndarr1)
ndarr2= np.eye(3)
print(ndarr2)

print(ndarr1 + ndarr2)
print(ndarr2 - ndarr1)
print(ndarr1 * ndarr2)
print(ndarr1 / ndarr2)
# Matrix multilication as per Linear Algebra
print(ndarr1 @ ndarr2) # Not clear how it calculate

# Transpose a matrix
np.transpose(ndarr1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[[ 0. -2. -3.]
 [-4. -4. -6.]
 [-7. -8. -8.]]
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
[[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


<ipython-input-29-de5cdf11a7d9>:10: RuntimeWarning: divide by zero encountered in divide
  print(ndarr1 / ndarr2)


In [ ]:
ndarr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1 + vec2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# MAX and MIN in a MATRIX
np.max(ndarr1)
np.min(ndarr1)

1

In [ ]:
# GENERATING RANDOM NO
print(np.random.rand(5))
print(np.random.rand(3,4))

[0.22578124 0.97583166 0.58742558 0.76092085 0.65282291]
[[0.49578694 0.31480298 0.73989316 0.85820292]
 [0.64014964 0.02423458 0.8696806  0.57295433]
 [0.85647741 0.64567209 0.85449033 0.70381572]]


In [ ]:
# GENERATING NORMAL RANDOM NO
# STANDARD DEVIATION (Mean 0 and Standard Deviation 1)
ndarr1=np.random.randn(5)
ndarr2=(np.random.randn(5,5))
print(np.mean(ndarr2))
print(np.std(ndarr2))

-0.3810012352035933
1.1480094971970214


In [ ]:
# RANDINT ( LOW, HIGH , NO)

print(np.random.randint(1,10,10))
print(np.random.randint(1,10,[5,5]))

[8 7 7 4 6 2 6 8 9 8]
[[4 1 6 1 3]
 [6 7 6 9 3]
 [8 4 7 3 8]
 [2 6 7 8 9]
 [8 9 8 4 8]]


In [ ]:
#ACCESSESSING THE NUMPY ARRAY
ndarray=np.arange(1,10,2)
ndarray[1]


3

In [ ]:
ndarr1= np.arange(1,10).reshape(3,3)
print(ndarr1)
ndarr1[1][1]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


5

In [ ]:
# Modifying the sub matrix will update the original matrix

org_matrix= np.random.rand(5,5)
print(org_matrix)
sub_matrix= org_matrix[1:3,3:5]
print(sub_matrix)
sub_matrix[:] = 3
print(sub_matrix)
print(org_matrix)

[[0.5068078  0.45139777 0.8430882  0.8609107  0.64473682]
 [0.66507801 0.31074235 0.48791898 0.06966133 0.5284197 ]
 [0.43113086 0.18647514 0.50714072 0.77852445 0.46296064]
 [0.09050631 0.78588305 0.03788381 0.91936921 0.27167459]
 [0.98374379 0.07518196 0.09154051 0.7563463  0.37642543]]
[[0.06966133 0.5284197 ]
 [0.77852445 0.46296064]]
[[3. 3.]
 [3. 3.]]
[[0.5068078  0.45139777 0.8430882  0.8609107  0.64473682]
 [0.66507801 0.31074235 0.48791898 3.         3.        ]
 [0.43113086 0.18647514 0.50714072 3.         3.        ]
 [0.09050631 0.78588305 0.03788381 0.91936921 0.27167459]
 [0.98374379 0.07518196 0.09154051 0.7563463  0.37642543]]


In [ ]:
# .Copy to create the Shallow Copy of list and array
org_matrix= np.random.rand(5,5)
print(org_matrix)
sub_matrix= org_matrix[1:3,3:5].copy() # creates a Shallow Copy
sub_matrix[:]=3
print(sub_matrix)
print(org_matrix)

[[0.75249506 0.34352717 0.22097425 0.77105036 0.01248793]
 [0.85795622 0.15132919 0.07229855 0.46927533 0.4616023 ]
 [0.6804014  0.22333001 0.44969585 0.59920352 0.53264095]
 [0.25871422 0.7217417  0.44195767 0.1247179  0.38374955]
 [0.73999316 0.7027219  0.70169563 0.78080577 0.79101697]]
[[3. 3.]
 [3. 3.]]
[[0.75249506 0.34352717 0.22097425 0.77105036 0.01248793]
 [0.85795622 0.15132919 0.07229855 0.46927533 0.4616023 ]
 [0.6804014  0.22333001 0.44969585 0.59920352 0.53264095]
 [0.25871422 0.7217417  0.44195767 0.1247179  0.38374955]
 [0.73999316 0.7027219  0.70169563 0.78080577 0.79101697]]


In [ ]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [ ]:
np.random.randint(10,20,1000)

array([15, 10, 18, 11, 18, 14, 15, 17, 18, 17, 10, 14, 10, 17, 15, 16, 14,
       11, 16, 12, 19, 14, 19, 10, 17, 18, 18, 18, 10, 16, 16, 18, 15, 12,
       18, 19, 10, 18, 13, 19, 14, 16, 16, 13, 14, 15, 11, 12, 14, 19, 19,
       19, 14, 11, 10, 17, 16, 14, 19, 18, 13, 16, 12, 15, 15, 12, 17, 19,
       10, 19, 17, 15, 17, 19, 18, 19, 10, 11, 17, 17, 19, 17, 19, 15, 19,
       18, 13, 18, 13, 10, 15, 16, 10, 14, 18, 14, 18, 11, 13, 11, 12, 17,
       17, 15, 19, 16, 15, 19, 17, 15, 18, 17, 12, 15, 14, 18, 16, 12, 16,
       13, 10, 13, 17, 19, 19, 19, 18, 19, 13, 16, 18, 12, 15, 15, 14, 15,
       10, 14, 10, 19, 12, 13, 17, 11, 14, 16, 12, 17, 16, 18, 17, 19, 11,
       13, 10, 10, 10, 16, 17, 10, 18, 13, 19, 11, 15, 18, 17, 18, 17, 11,
       12, 17, 13, 16, 19, 16, 13, 11, 19, 18, 11, 16, 17, 12, 11, 15, 13,
       15, 12, 15, 18, 16, 15, 15, 10, 14, 10, 18, 13, 10, 10, 18, 10, 12,
       16, 14, 12, 17, 14, 12, 18, 18, 17, 18, 14, 15, 18, 13, 17, 18, 11,
       11, 19, 15, 14, 12

In [ ]:
from google.colab import drive
drive.mount('/content/drive')



Mounted at /content/drive


In [ ]:
matrix1= np.random.randint(10,20,10).reshape(2,5)
print(matrix1)
np.save('/content/drive/MyDrive/Data/test',matrix1)

[[10 10 10 19 16]
 [17 15 10 13 15]]


In [ ]:
ls /content/drive/MyDrive/Data

In [ ]:
import pandas as pd
data = {'A': [1, 2,3], 'B': [3, 4, 5]}
df = pd.DataFrame(data)
print(df)

   A  B
0  1  3
1  2  4
2  3  5
