<a href="https://colab.research.google.com/github/RohitKumar1608/AI_ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Numpy takes list as an input and convert it to ndarray
import numpy as np

carlst = ['Tesla','Tata','Ford','Nissan']
lst=np.array(carlst)
print(lst)

['Tesla' 'Tata' 'Ford' 'Nissan']


In [4]:
# Matrix
lst= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(lst)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#arange
ndarr= np.arange(0,10,2)
print(ndarr)

[0 2 4 6 8]


In [10]:
# linspace
ndarr=np.linspace(0,5,10)
print(ndarr)

ndarr=np.linspace(10,20,10)
print(ndarr)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [4]:
# ZEROS (ROW, COLUMN)
ndarr = np.zeros ([3,5])
ndarr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# ONES (ROW,COLUM)
ndarr=np.ones([3,5])
ndarr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
ndarr=np.eye(3)
print(ndarr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Reshape
# Reshape don't alter the ndarr but can be asigned to new numpy array
ndarr=np.arange(0,10)
print(ndarr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
print(ndarr.reshape(2,5))
print(ndarr.reshape(5,2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
print(np.sin(4))
print(np.cos(4))
print(np.tan(4))
print(np.sin(ndarr))

-0.7568024953079282
-0.6536436208636119
1.1578212823495775
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [17]:
# exponential
print(np.exp(2))
print(np.exp(ndarr))

7.38905609893065
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [7]:
print(np.log(2.71))
print(np.log10(10))

0.9969486348916096
1.0


In [9]:
# Adding list concatenate the two list
l1= [1,2,3]
l2 =[4,5,6]
l1+l2

[1, 2, 3, 4, 5, 6]

In [12]:
l1= [1,2,3]
l2 =[4,5,6]
ndarr =np.array(l1) + np.array(l2)
ndarr

array([5, 7, 9])

In [15]:
arr1 = np.arange(1,6)
arr2 = np.arange(3,8)
print("addition", arr1+arr2)
print("substraction", arr2-arr1)
print("Multiplication", arr1 * arr2)
print("Division", arr1/arr2)
print("Inverse", 1/arr1)
print("Power", arr1 ** arr2)

addition [ 4  6  8 10 12]
substraction [2 2 2 2 2]
Multiplication [ 3  8 15 24 35]
Division [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse [1.         0.5        0.33333333 0.25       0.2       ]
Power [    1    16   243  4096 78125]


In [29]:
# MATRIX OPERATION
ndarr1= np.arange(1,10).reshape(3,3)
print(ndarr1)
ndarr2= np.eye(3)
print(ndarr2)

print(ndarr1 + ndarr2)
print(ndarr2 - ndarr1)
print(ndarr1 * ndarr2)
print(ndarr1 / ndarr2)
# Matrix multilication as per Linear Algebra
print(ndarr1 @ ndarr2) # Not clear how it calculate

# Transpose a matrix
np.transpose(ndarr1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[[ 0. -2. -3.]
 [-4. -4. -6.]
 [-7. -8. -8.]]
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
[[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


<ipython-input-29-de5cdf11a7d9>:10: RuntimeWarning: divide by zero encountered in divide
  print(ndarr1 / ndarr2)


In [30]:
ndarr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1 + vec2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 