<a href="https://colab.research.google.com/github/RohitKumar1608/AI_ML/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
lst= [1,2,3,4,5]
ndarr=np.array(lst)
print(pd.Series(lst))
print(pd.Series(ndarr))

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
#Changing indices to the name from number
#print(pd.Series(lst,index=['a','b','c','d','e']))
print(pd.Series(['Rohit','Priti','Anaisha','Avyaan'],index=['Father','Mother','Daughter','Son'],))

Father        Rohit
Mother        Priti
Daughter    Anaisha
Son          Avyaan
dtype: object


In [ ]:
student=['Anaisha','Priti','Avyaan','Anaisha']
grades = ['A','B','C','D']
pd.DataFrame({'Student':student,'grades':grades})


Student grades
0  Anaisha      A
1    Priti      B
2   Avyaan      C
3  Anaisha      D

In [ ]:
# Accessing the Pandas Series

operators =['Visible','AT&T','Verizon']
revenues = [100,200,300]

a=pd.Series(revenues,index=operators)
a[:2]
#a[-2:]
a[0:3:2]
a.

Visible    100
Verizon    300
dtype: int64

40

In [ ]:
import numpy as np
import pandas as pd
a= np.array(([13,35,74,48],[23,37,37,38],[73,39,93,39]))
a[0:3,1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [ ]:
a= np.arange(10)
print(a)
a[0:7]=5
print(a)

[0 1 2 3 4 5 6 7 8 9]
[5 5 5 5 5 5 5 7 8 9]


In [ ]:
import numpy as np
d = np.arange(0,10)
d<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
flowers = pd.Series([2,3,5,4], index=['lily','rose','daisy','lotus'])
flowers['daisy']

5

In [ ]:
data = {'customer': ['101', '102', '103', '104','101','103'],
        'category': ['cat2', 'cat2', 'cat1', 'cat3','cat2','cat1'],
        'important':['yes','no','yes','yes','yes','yes'],
        'sales': [123,52,214,663,204,453]}

# Create DataFrame
df = pd.DataFrame(data)

print(df)
#df.loc[[1,2],['customer','sales']]
df.drop('sales',axis=1,inplace=True)
df

  customer category important  sales
0      101     cat2       yes    123
1      102     cat2        no     52
2      103     cat1       yes    214
3      104     cat3       yes    663
4      101     cat2       yes    204
5      103     cat1       yes    453


customer category important
0      101     cat2       yes
1      102     cat2        no
2      103     cat1       yes
3      104     cat3       yes
4      101     cat2       yes
5      103     cat1       yes

In [ ]:
student=['Rohit','']